import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head><link rel="stylesheet" href="https://rsms.me/inter/inter.css"/></head>
      <body className='bg-[#a0a0a0]'  >{children}</body>
    </html>
  )
}
